# Generated by Django 2.0.5 on 2018-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cost',
            field=models.TextField(null=True),
        ),
    ]
