# Generated by Django 2.0.5 on 2018-06-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0004_place_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conciergerie.Service'),
        ),
    ]
