# Generated by Django 2.0.5 on 2018-06-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0005_place_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='service',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conciergerie.Service'),
        ),
    ]
