# Generated by Django 2.0.5 on 2018-06-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0006_auto_20180621_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conciergerie.Place'),
        ),
    ]
