# Generated by Django 2.0.5 on 2018-06-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0007_auto_20180621_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('type', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciergerie.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciergerie.Utilisateur')),
            ],
        ),
    ]
