# Generated by Django 2.0.5 on 2018-06-21 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conciergerie', '0008_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='activite',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciergerie.TypeActivite'),
        ),
    ]
